# Generated by Django 3.2.3 on 2021-07-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uznews', '0003_stopwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('views', models.IntegerField()),
                ('posted_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=20)),
            ],
        ),
    ]
