# Generated by Django 3.2.3 on 2021-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uznews', '0005_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
