# Generated by Django 3.2.3 on 2021-08-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uznews', '0006_auto_20210729_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created_at',)},
        ),
    ]
