# Generated by Django 3.2.3 on 2021-08-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uznews', '0007_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-posted_at',)},
        ),
    ]
