# Generated by Django 3.2.3 on 2021-11-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uznews', '0008_alter_news_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StopWords',
        ),
    ]
