# Generated by Django 3.2.3 on 2022-02-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uznews', '0012_auto_20220215_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='users',
            field=models.ManyToManyField(to='uznews.Profile'),
        ),
    ]
