# Generated by Django 3.2.3 on 2022-02-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uznews', '0013_alter_keywords_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='users',
            field=models.ManyToManyField(related_name='member', to='uznews.Profile'),
        ),
    ]
