# Generated by Django 3.2.3 on 2022-02-15 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uznews', '0015_alter_keywords_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
