# Generated by Django 3.2.3 on 2022-02-16 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uznews', '0016_auto_20220215_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='users',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
